version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=techmeet
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: docker.appdirect.tools/postgres:15-alpine
    environment:
      - POSTGRES_DB=techmeet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d techmeet"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  postgres_data:
